---
title: "Ahas Method"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: 
  html_document:
    toc: true 
    toc_depth: 4  
    number_sections: true  
    theme: united  
    highlight: tango  
    toc_float: true   
    code_folding: hide
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r load_library}
library(tidyverse)
library(magrittr)
library(sf)
library(lubridate)
library(furrr)
library(gridExtra)
library(tidycensus)
library(homelocator)
```

# Load data
```{r load_data, message=FALSE, warning=FALSE}
if (file.exists(here::here("data/lexington2012_2017.rds"))) {
   df <- readRDS(here::here("data/lexington2012_2017.rds"))
 } else {
   df <- read_csv(here::here("data/lexington-with-GEOID-2012-2017.csv")) %>% 
     select(c(u_id, GEOID, created_at)) %>% 
     mutate(u_id = as.character(u_id),
            GEOID = as.character(GEOID))
   saveRDS(df, here::here("data/lexington2012_2017.rds"))  # save to rds 
 }

df <- df %>% 
  derive_timestamp(created_at)

# nest data 
df_nest <- nest_dataframe(df, u_id)
head(df_nest)
```

# Data filtering 
```{r data_filtering, message=FALSE, warning=FALSE}
ahas_filtered <- df_nest %>% 
  summarise_var(counts_per_user = n(), 
                distinct_loc_per_user = n_distinct(GEOID)) %>% 
  summarise_groupVar(vars(GEOID), 
                     vars(counts_per_loc = n(), 
                          distinct_date_per_loc = n_distinct(date))) %>% 
  arrange_groupVar(u_id, counts_per_loc, distinct_date_per_loc) %>% 
  top_n(., 1, counts_per_loc) %>%  # get top one loc
  unnest() %>% 
  nest_multigroups(vars(u_id, counts_per_user)) %>% 
  summarise_groupVar(vars(GEOID, year, month), 
                     vars(distinct_day_per_month = n_distinct(day))) %>% 
  filter_var(distinct_day_per_month > 7) %>% # top one loc must has at least 7 distinct day 
  select(u_id, counts_per_user) %>% 
  unique() %>% 
  left_join(., df) %>% 
  nest_dataframe(u_id) %>% 
  summarise_groupVar(vars(GEOID, year, month, counts_per_user), 
                      vars(distinct_day_per_month = n_distinct(day))) %>% 
  filter_var(distinct_day_per_month > 2) %>% # each loc must has at least 2 distinct day 
  arrange_var(counts_per_user) %>% 
  remove_bots(top_user_percent = 0.1) 
head(ahas_filtered)
```


```{r home_ahas, message=FALSE, warning=FALSE}
time_line <- chron::times("17:00:00") %>% as.numeric()
home_ahas <- ahas_filtered %>% 
  add_col(time = format(created_at, format="%H:%M:%S") %>% chron::times()) %>% 
  nest_dataframe(u_id) %>% 
  summarise_groupVar(vars(GEOID),
                     vars(distinct_date_per_loc = n_distinct(date),
                           counts_per_loc = n(),
                           avg_time = mean(time),
                           sd_time = sd(time))) %>% 
  add_col(score_avg_time = if_else(avg_time > time_line, 1, 0)) %>% 
  add_col(score_sd_time = if_else(sd_time > 0.175, 1, 0)) %>% 
  add_col(score = rowSums(.[, c("score_avg_time", "score_sd_time")])) %>% 
  nest_dataframe(u_id) %>% 
  extract_home(score >= 1, distinct_date_per_loc, counts_per_loc)
write_csv(home_ahas, path = "result_ahas.csv")
```






