---
title: "Introduction of homelocator package"
author: "Chen Qingqing"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Load package 

```{r warning=FALSE, message=FALSE}

library(dplyr)
library(tidyverse)
library(readr)
library(RColorBrewer)
library(sf)
library(tmap)
library(tmaptools)

tmap_mode("view")
```


```{r load data}

grid_300 <- readRDS(file = "data/grid_300.rda")
grid_300 <- grid_300[[1]]

df_subzone <- read_sf("data/Shp/MP14_SUBZONE_NO_SEA_PL.shp") %>% 
  st_transform(., "+init=epsg:3414") %>% 
  group_by(PLN_AREA_N) %>% 
  dplyr::summarise(., count= n()) %>% 
  select(-count) 

grid <- st_make_grid(df_subzone, cellsize = c(300,300), square = FALSE) %>% st_sf(grid_id = 1:length(.))  # create grid with cellsize

```


```{r identify tweet users have airport homelocation}

airport <- readRDS(file = "data/df_home_20.rds") %>% 
  separate(home,c("grid_id","grid_id2"),sep = ";") %>% 
  mutate(grid_id= as.numeric(grid_id), grid_id2= as.numeric(grid_id2)) %>%   filter(!grid_id=="NA") %>% 
  left_join( grid_300,by = "grid_id") %>% 
  select(-counts) %>% 
  setNames(c("u_id","grid_id_1","grid_id","grid_id_geometry")) %>% 
  left_join(grid_300,by = "grid_id") %>% 
  select(-counts) %>% 
  setNames(c("u_id","grid_id_1","grid_id_2","geometry_1","geometry_2")) %>% 
  filter(grid_id_1==5694|grid_id_2==5694)

tweets_g300 <- readRDS(file = "data/tweets_with_300m_grid.rda")

tweeter_airport <- tweets_g300 %>%
  filter(u_id %in% airport$u_id) %>% 
  group_by(u_id) %>% 
  summarise(tweet_counts=n())

```



## testing of indivisual
```{r airport h_loc tweet temperal distribution}

indv_user_temporal_dis <- function(user) {
indv_user_top_grid <- tweets_g300 %>% filter(u_id == user) %>% 
  filter(grid_id == 5694 |grid_id== 5693) 

indv_hour_count <- indv_user_top_grid %>% 
  group_by(hour) %>% 
  summarise(counts=n())

ggplot(indv_user_top_grid, aes(x=hour)) + 
 geom_histogram(binwidth=1,fill="grey")+
 stat_bin(binwidth=1, geom="text", colour="black", size=3.5, aes(label=..count..), vjust=-0.3)+
  xlim(1,24)+
  ggtitle("Tweets @ hour ")
}

```

```{r plot airport location temporal distribution warning=FALSE, message=FALSE}
indv_user_temporal_dis(tweeter_airport$u_id[77])
```


```{r plot user's tweet distribution on map}
indv_user_map_plot <- function(user){
indv_user <- tweets_g300 %>% filter(u_id == user) %>%
  group_by(grid_id) %>% 
  summarise(tweets_counts=n()) %>% 
  filter(tweets_counts>1) %>% 
  st_drop_geometry() %>% 
  left_join(grid) %>% 
  st_sf()

tm_shape(df_subzone)+
  tm_polygons(col = "grey", alpha = 0.2, border.col = "white")+
  tm_shape(indv_user) +
  tm_fill("tweets_counts",palette=brewer.pal("BuPu",n = 5),
          n=3,style = "fisher",
          title="Tweet User")
}
```

```{r}
indv_user_map_plot(tweeter_airport$u_id[77])
```

```{r plot user's other grid's temporal distribution warning=FALSE, message=FALSE}

indv_user_temporal_dis_next <- function(user,n_grid) {
indv_user_top_grid <- tweets_g300 %>% filter(u_id == user) %>% 
  filter(grid_id == n_grid) 

indv_hour_count <- indv_user_top_grid %>% 
  group_by(hour) %>% 
  summarise(counts=n())

ggplot(indv_user_top_grid, aes(x=hour)) + 
 geom_histogram(binwidth=1,fill="grey")+
 stat_bin(binwidth=1, geom="text", colour="black", size=3.5, aes(label=..count..), vjust=-0.3)+
  xlim(1,24)+
  ggtitle("Tweets @ hour ")
}

indv_user_temporal_dis_next(tweeter_airport$u_id[77],2461)
```



