---
title: "Homelocator Method"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: 
  html_document:
    toc: true 
    toc_depth: 4  
    number_sections: true  
    theme: united  
    highlight: tango  
    toc_float: true   
    code_folding: hide
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_library, message=FALSE, warning=FALSE}
library(homelocator)
library(dplyr)
library(tidyverse)
library(readr)
```

```{r load_data, message=FALSE, warning=FALSE}
if (file.exists(here::here("data/lexington2012_2017.rds"))) {
   df <- readRDS(here::here("data/lexington2012_2017.rds"))
 } else {
   df <- read_csv(here::here("data/lexington-with-GEOID-2012-2017.csv")) %>% 
     select(c(u_id, GEOID, created_at)) %>% 
     mutate(u_id = as.character(u_id),
            GEOID = as.character(GEOID))
   saveRDS(df, here::here("data/lexington2012_2017.rds"))  # save to rds 
 }

df <- derive_timestamp(df, created_at)

# nest data 
df_nest <- nest_dataframe(df, u_id)
head(df_nest)
```

```{r data_filtering, message=FALSE, warning=FALSE}
qq_filtered <- df_nest %>% 
  summarise_var(counts_per_user = n(), 
                distinct_loc_per_user = n_distinct(GEOID)) %>% 
  filter_var(counts_per_user > 10) %>% 
  filter_var(distinct_loc_per_user > 10) %>% 
  summarise_groupVar(vars(GEOID), 
                     vars(counts_per_loc = n(), 
                          distinct_hour_per_loc = n_distinct(hour_of_day), 
                          distinct_day_per_loc = n_distinct(date), 
                          time_period_per_loc = as.numeric(max(created_at) - min(created_at), "days"))) %>% 
  filter_var(counts_per_loc > 10) %>% 
  filter_var(distinct_hour_per_loc > 10) %>% 
  filter_var(distinct_day_per_loc > 10) %>% 
  filter_var(time_period_per_loc > 10) %>% 
  arrange_var(counts_per_user) %>% 
  remove_bots(top_user_percent = 0.01) 
head(qq_filtered)
```

```{r}
fig1 <- qq_filtered %>% 
  mutate(month = lubridate::month(created_at, label = T, abbr = T)) %>% 
  group_by(month) %>%
  summarise(n_id = n_distinct(u_id)) %>% 
  ggplot(., aes(x = month, y = n_id)) + 
  geom_bar(stat = "identity") +
  geom_text(aes(label = n_id), vjust=-0.8, size=3, color = "black") + 
  labs(
    x = "Month",
    y = "Number of users",
    subtitle = 'The Distribution of the Number of Users per month',
    caption = 'Figure 1'
  )

fig2 <- qq_filtered %>% 
  mutate(month = lubridate::month(created_at, label = T, abbr = T)) %>% 
  group_by(month) %>%
  summarise(n = n()) %>% 
  ggplot(., aes(x = month, y = n)) + 
  geom_bar(stat = "identity") +
  geom_text(aes(label = n), vjust=-0.8, size=3, color = "black") + 
  labs(
    x = "Month",
    y = "Number of Tweets",
    subtitle = 'The Distribution of the Number of Tweets per month',
    caption = 'Figure 2'
  )

gridExtra::grid.arrange(fig1, fig2, ncol = 1)
```


```{r}
levels <- c(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23) %>% as.character()
cbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

fig3 <- qq_filtered %>% 
  mutate(day_of_week = lubridate::wday(created_at, label = T, abbr = T)) %>% 
  mutate(hour_of_day = as.character(hour_of_day), 
         hour_of_day = factor(hour_of_day, levels = levels)) %>% 
  group_by(day_of_week, hour_of_day) %>% 
  summarise(n_tweets = n()) %>% 
  group_by(day_of_week) %>% 
  mutate(total_tweets = sum(n_tweets), 
         freq = n_tweets/total_tweets) %>% 
  ungroup() %>% 
    ggplot(., aes(x=hour_of_day, y = freq, color = day_of_week)) +
    geom_line(aes(group = day_of_week)) + 
    geom_point() +
    scale_colour_manual(values=cbPalette) + 
    geom_vline(xintercept = 10, linetype="dotted") + 
    geom_text(aes(x = 6, y=0.075,  label="Rest Time"), colour="black") + 
    geom_vline(xintercept = 19, linetype="dotted") + 
    geom_text(aes(x = 14, y=0.075,  label="Work Time"), colour="black") + 
    geom_text(aes(x = 22, y=0.075,  label="Rest Time"), colour="black") + 
    theme(legend.position = c(0.8, 0.1),
          panel.background = element_blank(),
          axis.line = element_line("black"),
          legend.text=element_text(size=7),
          legend.direction="horizontal") + 
    labs(
      x = "Hour of the day", 
      y = "Tweet Frequency", 
      color = "Day of Week",
      title = 'Tweets publishing activity during a week',
      caption = 'Figure 3'
    )

fig4 <- qq_filtered %>% 
  mutate(day_of_week = lubridate::wday(created_at, label = T, abbr = T)) %>% 
  mutate(hour_of_day = as.character(hour_of_day), 
         hour_of_day = factor(hour_of_day, levels = levels)) %>% 
  group_by(day_of_week, hour_of_day) %>% 
  summarise(n_tweets = n()) %>% 
  group_by(day_of_week) %>% 
  mutate(total_tweets = sum(n_tweets), 
         freq = n_tweets/total_tweets) %>% 
  ungroup() %>% 
    ggplot(., aes(x=hour_of_day, y = freq, color = day_of_week)) +
    geom_line(aes(group = day_of_week)) + 
    geom_point() +
    scale_colour_manual(values=cbPalette) + 
    geom_vline(xintercept = 7, linetype="dotted") + 
    geom_text(aes(x = 5, y=0.077,  label="Non-early morning"), colour="black") + 
    geom_vline(xintercept = 13, linetype="dotted") + 
    geom_text(aes(x = 10, y=0.077,  label="Early Morning"), colour="black") + 
    geom_text(aes(x = 18, y=0.077,  label="Non-early morning"), colour="black") + 
    theme(legend.position = c(0.8, 0.1),
          panel.background = element_blank(),
          axis.line = element_line("black"),
          legend.text=element_text(size=7),
          legend.direction="horizontal") + 
    labs(
      x = "Hour of the day", 
      y = "Tweet Frequency", 
      color = "Day of Week",
      title = 'Tweets publishing activity during a week',
      caption = 'Figure 4'
    )

gridExtra::grid.arrange(fig3, fig4, ncol = 1)
```


```{r data_expanded, message=FALSE, warning=FALSE}
qq_expanded <- qq_filtered %>% 
  add_col(week = if_else(day_of_week %in% c(1,7), 1, 2)) %>%  # 1 for weekend, 2 for weekday 
  add_col(numeric_time = lubridate::hour(created_at) + lubridate::minute(created_at) / 60 + lubridate::second(created_at) / 3600) %>% 
  add_col(rest_or_work = if_else(numeric_time >= 9 & numeric_time <= 18, 2, 1)) %>% # 1 for rest time, 2 for work time 
  add_col(early_or_late = if_else(numeric_time >= 6 & numeric_time <= 12, 1, 2)) # 1 for early morning, 2 for late afternoon and night 
```


```{r data_score, message=FALSE, warning=FALSE}
qq_scored <- qq_expanded %>% 
  nest_dataframe(u_id) %>% 
  summarise_var(distinct_day_of_week = n_distinct(day_of_week),  
                distinct_month = n_distinct(month)) %>% 
  summarise_groupVar(vars(week), vars(counts_week = n())) %>% 
  add_groupCol(vars(u_id), vars(percent_week = counts_week/sum(counts_week))) %>% 
  nest_dataframe(u_id) %>% 
  summarise_groupVar(vars(rest_or_work), vars(counts_rest_or_work = n())) %>% 
  add_groupCol(vars(u_id), vars(percent_rest_or_work = counts_rest_or_work/sum(counts_rest_or_work))) %>% 
  nest_dataframe(u_id) %>% 
  filter_nest(rest_or_work == 1 & percent_rest_or_work >= 0.5) %>% 
  score_user(u_id, score_counts_per_loc = 0.1 * (counts_per_loc/max(counts_per_loc))) %>% 
  score_user(u_id, score_distinct_hour_per_loc = 0.1 * (distinct_hour_per_loc/24)) %>% 
  score_user(u_id, score_distinct_day_per_loc = 0.1 * (distinct_day_per_loc/max(distinct_day_per_loc))) %>% 
  score_user(u_id, score_time_period_per_loc = 0.1 * (time_period_per_loc/max(as.numeric(time_period_per_loc)))) %>% 
  score_user(u_id, score_percent_week = 0.2 * (percent_week)) %>% 
  score_user(u_id, score_percent_rest_or_work = 0.2 * (percent_rest_or_work)) %>% 
  score_user(u_id, score_distinct_day_of_week = 0.1 * (distinct_day_of_week/7)) %>% 
  score_user(u_id, score_distinct_month = 0.1 * (distinct_month/12)) %>% 
  sum_score(u_id, GEOID, score_counts_per_loc, score_distinct_hour_per_loc, score_distinct_day_per_loc, score_time_period_per_loc, score_percent_week, score_percent_rest_or_work, score_distinct_day_of_week, score_distinct_month)
```

```{r home_extract, message=FALSE, warning=FALSE}
home_qq <- qq_scored %>%
  nest_dataframe(u_id) %>% 
  extract_home(score > 0, score)
head(home_qq)
write_csv(home_qq, path = "result_qingqing.csv")
```

