---
title: 'SG Tweets: Home Location'
author: "Chen Qinqqing"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: 
  html_document:
    toc: true 
    toc_depth: 4  
    number_sections: true  
    theme: united  
    highlight: tango  
    toc_float: true   
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r load_library, message=FALSE, warning=FALSE}
#library(homelocator)
library(dplyr)
library(tidyverse)
library(readr)
library(sf)
library(proj4)
library(tmap)
library(classInt)
library(RColorBrewer)
library(ggpubr)
```



```{r}
df <- readRDS(here::here("data/test_df.rds"))

loc_hlc <- homelocator::identify_loc(df, user = "u_id", timestamp = "created_at", location = "grid_id", recipe = "HLC", show_n_loc = 1)
loc_osn <- homelocator::identify_loc(df, user = "u_id", timestamp = "created_at", location = "grid_id", recipe = "OSN", show_n_loc = 1)
loc_mpd <- homelocator::identify_loc(df, user = "u_id", timestamp = "created_at", location = "grid_id", recipe = "MPD", show_n_loc = 1)
loc_freq <- homelocator::identify_loc(df, user = "u_id", timestamp = "created_at", location = "grid_id", recipe = "FREQ", show_n_loc = 1)
```

# Load dataset
```{r}
tweets <- readRDS(here::here("data/tweets_ori.rds"))
tweets_sf <- readRDS(here::here("data/tweets_gridID.rds"))

df_subzone <- read_sf(here::here("data/Shp/MP14_SUBZONE_NO_SEA_PL.shp")) %>% st_transform(., "+init=epsg:3414")
grids <- readRDS(here::here("data/grid_750.rds"))

#homelocator recipe
if (file.exists(here::here("data/hm_hlc.csv"))){
  hm_hlc <- read_csv(here::here("data/hm_hlc.csv")) %>% mutate(name = "HLC")
} else {
  hm_hlc <- homelocator::identify_loc(tweets %>% st_set_geometry(NULL), user = "u_id", timestamp = "created_at", location = "grid_id", recipe = "HLC", show_n_loc = 1)
  write_csv(hm_hlc, path = here::here("data/hm_hlc.csv"))
}

#online social network recipe
if (file.exists(here::here("data/hm_osn.csv"))) {
  hm_osn <- read_csv(here::here("data/hm_osn.csv")) %>% mutate(name = "OSN")
} else{
  hm_osn <- homelocator::identify_loc(tweets %>% st_set_geometry(NULL), user = "u_id", timestamp = "created_at", location = "grid_id", recipe = "OSN", show_n_loc = 1)
  write_csv(hm_osn, path = here::here("data/hm_osn.csv"))
}

#mobile positioning data
if (file.exists(here::here("data/hm_mpd.csv"))){
  hm_mpd <- read_csv(here::here("data/hm_mpd.csv")) %>% mutate(name = "MPD")
} else {
  hm_mpd <- homelocator::identify_loc(tweets %>% st_set_geometry(NULL), user = "u_id", timestamp = "created_at", location = "grid_id", recipe = "MPD", show_n_loc = 1)
  write_csv(hm_mpd, path = here::here("data/hm_mpd.csv"))
}
  
#frequency
if (file.exists(here::here("data/hm_freq.csv"))){
  hm_frq <- read_csv(here::here("data/hm_freq.csv")) %>% mutate(name = "FREQ")
} else {
  hm_frq <- homelocator::identify_loc(tweets %>% st_set_geometry(NULL), user = "u_id", timestamp = "created_at", location = "grid_id", recipe = "FREQ", show_n_loc = 1)
  write_csv(hm_frq, path = here::here("data/hm_freq.csv"))
}

hm_full <- bind_rows(hm_hlc, hm_osn, hm_mpd, hm_frq) %>% left_join(., grids, by = c("home" = "grid_id")) 
```


# Overview home results Odds Ratio
```{r}
color8  <- c("#ffffcc", "#ffeda0", "#fed976", "#feb24c", "#fd8d3c", "#fc4e2a", "#e31a1c", "#b10026")
tweets_sub <- tweets %>% st_set_geometry(NULL) %>% select(c(u_id, grid_id)) %>% unique()

all_users_sg <- tweets$u_id %>% n_distinct()
all_users_grid <- tweets_sub %>% group_by(grid_id) %>% summarise(users_grid = n_distinct(u_id))

all_hm_users_hlc_sg <- nrow(hm_hlc)
all_hm_users_osn_sg <- nrow(hm_osn)
all_hm_users_mpd_sg <- nrow(hm_mpd)
all_hm_users_frq_sg <- nrow(hm_frq)


OR_hm_hlc <- hm_hlc %>% 
  group_by(home) %>% 
  summarise(hm_users_grid = n_distinct(u_id)) %>% 
  left_join(., grids, by = c("home" = "grid_id")) %>% 
  left_join(., all_users_grid, by = c("home" = "grid_id")) %>% 
  mutate(OR = (hm_users_grid/all_hm_users_hlc_sg)/(users_grid/all_users_sg),
         method = "HLC") 

OR_hm_osn <- hm_osn %>% 
  group_by(home) %>% 
  summarise(hm_users_grid = n_distinct(u_id)) %>% 
  left_join(., grids, by = c("home" = "grid_id")) %>% 
  left_join(., all_users_grid, by = c("home" = "grid_id")) %>% 
  mutate(OR = (hm_users_grid/all_hm_users_osn_sg)/(users_grid/all_users_sg),
         method = "OSN") 

OR_hm_mpd <- hm_mpd %>% 
  group_by(home) %>% 
  summarise(hm_users_grid = n_distinct(u_id)) %>% 
  left_join(., grids, by = c("home" = "grid_id")) %>% 
  left_join(., all_users_grid, by = c("home" = "grid_id")) %>% 
  mutate(OR = (hm_users_grid/all_hm_users_mpd_sg)/(users_grid/all_users_sg),
         method = "MPD")

OR_hm_frq <- hm_frq %>% 
  group_by(home) %>% 
  summarise(hm_users_grid = n_distinct(u_id)) %>% 
  left_join(., grids, by = c("home" = "grid_id")) %>% 
  left_join(., all_users_grid, by = c("home" = "grid_id")) %>% 
  mutate(OR = (hm_users_grid/all_hm_users_frq_sg)/(users_grid/all_users_sg),
         method = "FREQ") 
OR_hm_full <- rbind(OR_hm_hlc, OR_hm_mpd, OR_hm_osn, OR_hm_frq) %>% 
  st_as_sf() %>% 
  mutate(method = factor(method, levels = c("OSN", "MPD", "HLC", "FREQ")))

ma1 <- tm_shape(grids) +
  tm_borders(col = "grey") +
  tm_shape(OR_hm_full %>% filter(method == "HLC")) +
  tm_fill("OR", palette = color8,
          n = 8, style = "fisher",
          legend.hist = TRUE,
          title = "Odds Ratio") +
  tm_layout(
            title = "HLC",
            title.position = c("left", "top"),
            legend.outside = F,
            legend.position = c("right", "bottom"),
            legend.hist.height = 0.1,
            legend.hist.width = 0.3,
            legend.hist.size = 0.5)

ma2 <-tm_shape(grids) +
  tm_borders(col = "grey") +
  tm_shape(OR_hm_full %>% filter(method == "OSN")) +
  tm_fill("OR", palette = color8,
          n = 8, style = "fisher",
          legend.hist = TRUE,
          title = "Odds Ratio") +
  tm_layout(
    title = "OSN",
            title.position = c("left", "top"),
            legend.outside = F,
            legend.position = c("right", "bottom"),
            legend.hist.height = 0.1,
            legend.hist.width = 0.3,
            legend.hist.size = 0.5)

ma3 <- tm_shape(grids) +
  tm_borders(col = "grey") +
  tm_shape(OR_hm_full %>% filter(method == "MPD")) +
  tm_fill("OR", palette = color8,
          n = 8, style = "fisher",
          legend.hist = TRUE,
          title = "Odds Ratio") +
  tm_layout(
    title = "MPD",
            title.position = c("left", "top"),
            legend.outside = F,
            legend.position = c("right", "bottom"),
            legend.hist.height = 0.1,
            legend.hist.width = 0.3,
            legend.hist.size = 0.5)

ma4 <- tm_shape(grids) +
  tm_borders(col = "grey") +
  tm_shape(OR_hm_full %>% filter(method == "FREQ")) +
  tm_fill("OR", palette = color8,
          n = 8, style = "fisher",
          legend.hist = TRUE,
          title = "Odds Ratio") +
  tm_layout(
    title = "FREQ",
            title.position = c("left", "top"),
            legend.outside = F,
            legend.position = c("right", "bottom"),
            legend.hist.height = 0.1,
            legend.hist.width = 0.3,
            legend.hist.size = 0.5)
tmap_arrange(ma1, ma2, ma3, ma4, nrow = 2, ncol = 2)
```


# Percentage of users for different number of homes from common users 
```{r}
users_hlc <- hm_hlc$u_id
users_osn <- hm_osn$u_id
users_frq <- hm_frq$u_id
users_mpd <- hm_mpd$u_id

same_users <- intersect(intersect(intersect(users_hlc, users_osn), users_frq), users_mpd)

df_same <- hm_full %>% 
  filter(u_id %in% same_users) %>%
  st_as_sf() %>% st_centroid()

#users that be able to determine their homes by all four methods
n_same_users <- df_same$u_id %>% n_distinct()
percent_same_users <- n_same_users/all_users_sg


df_n_homes <- hm_full %>% 
  select(c(u_id, home, name)) %>% 
  filter(u_id %in% same_users) %>% 
  group_by(u_id) %>% 
  summarise(n_hm = n_distinct(home)) 
  
df_n_homes$n_hm %>% table() 
df_n_homes$n_hm %>% table() %>% prop.table() %>% round(., 4)
```

# Different results

## One home - 4 results are same 

### Common users character 
```{r}
one_home <- df_n_homes %>% 
  filter(n_hm == 1) %>% 
  mutate(method = "4 approaches") %>% 
  left_join(., hm_full) %>% 
  select(-c(n_hm, name)) %>% 
  unique() %>% 
  st_as_sf()

user_1hm <- one_home$u_id %>% unique()
user_1hm_tweets <- tweets %>% filter(u_id %in% user_1hm)

dens_tweets <- user_1hm_tweets %>% 
  st_set_geometry(NULL) %>% 
  group_by(grid_id) %>% 
  summarise(n_tweets = n()) %>% 
  mutate(norm_n_tweets = (n_tweets - min(n_tweets))/(max(n_tweets)-min(n_tweets))) %>% 
  inner_join(., grids) %>% 
  st_as_sf()
dens_users <- user_1hm_tweets %>% 
  st_set_geometry(NULL) %>% 
  group_by(grid_id) %>%
  summarise(n_users = n_distinct(u_id)) %>% 
  mutate(norm_n_users = (n_users - min(n_users))/(max(n_users)-min(n_users))) %>% 
  inner_join(., grids) %>% 
  st_as_sf() 
dens_home_users <- one_home %>% 
  st_set_geometry(NULL) %>% 
  select(c(u_id, home)) %>% 
  unique() %>% 
  group_by(home) %>% 
  summarise(n_users_home = n_distinct(u_id)) %>% 
  mutate(norm_n_users_home = (n_users_home - min(n_users_home))/(max(n_users_home)-min(n_users_home))) %>%
  left_join(., grids, by = c("home" = "grid_id")) %>% 
  st_as_sf() 
```



```{r}
pop2015 <- read_sf(here::here("data/pop2015/PLAN_BDY_DWELLING_TYPE_2015.shp")) %>% 
  st_transform(., "+init=epsg:3414") 
zone_4326 <- df_subzone %>% st_transform(4326) 
zone_grids <- df_subzone %>% st_join(., grids)
```

```{r}
## tweets distribution
h1_p1 <- tm_shape(grids) + 
  tm_borders(col = "grey") + 
  tm_shape(dens_tweets) +
  tm_fill("norm_n_tweets", palette = color8,
          n = 8, style = "fisher", 
          legend.hist = TRUE,
          title = "Normalized Tweets"
          ) +
  tm_layout(
            title = "Distribution of Tweets",
            title.position = c("left", "top"),
            title.size = 0.8,
            legend.outside = F,
            legend.position = c("right", "bottom"),
            legend.title.size  = 0.8,
            legend.hist.height = 0.1,
            legend.hist.width = 0.3,
            legend.hist.size = 0.5)
## twitter users distribution
h1_p2 <- tm_shape(grids) + 
  tm_borders(col = "grey") + 
  tm_shape(dens_users) + 
  tm_fill("norm_n_users", palette = color8,
          n = 8, style = "fisher", 
          legend.hist = TRUE,
          title = "Normalized Users"
          ) +
  tm_layout(
            title = "Distribution of Twitter Users",
            title.position = c("left", "top"),
    title.size = 0.8,
            legend.outside = F,
            legend.position = c("right", "bottom"),
            legend.title.size  = 0.8,
            legend.hist.height = 0.1,
            legend.hist.width = 0.3,
            legend.hist.size = 0.5)
## Inferred home/residents distribution
h1_p3 <-tm_shape(grids) + 
  tm_borders(col = "grey") + 
  tm_shape(dens_home_users) + 
  tm_fill("norm_n_users_home", palette = color8,
          n = 8, style = "fisher", 
          legend.hist = TRUE,
          title = "Normalized Users"
          ) +
  tm_layout(
            title = "Identified Residents",
            title.position = c("left", "top"),
    title.size = 0.8,
            legend.outside = F,
            legend.position = c("right", "bottom"),
            legend.title.size  = 0.8, 
            legend.hist.height = 0.1,
            legend.hist.width = 0.3,
            legend.hist.size = 0.5)

## real residents distribution
raw_pop <- tm_shape(df_subzone) + 
  tm_borders(col = "grey20") + 
  tm_shape(pop2015) + 
  tm_fill("TOTAL", palette = color8,
          n = 8, style = "fisher", 
          legend.hist = TRUE,
          title = "Number of Residents"
          ) +
  tm_layout(
            title = "Singapore Residents in 2015",
            title.position = c("left", "top"), 
     title.size = 0.8,
            legend.outside = F,
            legend.position = c("right", "bottom"),
            legend.title.size  = 0.8,
            legend.hist.height = 0.1,
            legend.hist.width = 0.3,
            legend.hist.size = 0.5)

library(grid)
grid.newpage()
pushViewport(viewport(layout = grid.layout(nrow = 2, ncol = 2)))
print(h1_p1, vp = viewport(layout.pos.row = 1, layout.pos.col = 1))
print(h1_p2, vp = viewport(layout.pos.row = 1, layout.pos.col = 2))
print(raw_pop, vp = viewport(layout.pos.row = 2, layout.pos.col = 1))
print(h1_p3, vp = viewport(layout.pos.row = 2, layout.pos.col = 2))
```

### real and inferred residents correlation 
```{r}
inferred_resids <- pop2015 %>% 
  select(c(PLN_AREA_N, TOTAL)) %>% 
  st_join(., one_home) %>% 
  st_set_geometry(NULL) %>% 
  group_by(PLN_AREA_N) %>% 
  summarise(n = n())
actual_resides <- pop2015 %>% 
  st_set_geometry(NULL) %>% 
  select(c(PLN_AREA_N, TOTAL))

residents <- left_join(inferred_resids, actual_resides) %>% 
  mutate(norm_n = n/sum(n),
         norm_total = TOTAL/sum(TOTAL))

ggscatter(residents, x = "norm_n", y = "norm_total",
  add = "reg.line") +
  stat_cor(label.y = 0.065) +
  stat_regline_equation(label.y = 0.07) + 
  ggrepel::geom_text_repel(aes(label=PLN_AREA_N), size = 2.5) +
  theme(panel.background=element_rect(fill = "white", colour = "black")) + 
  labs(x = "Normalized number of inferred residents",
       y = "Normalized number of actual residents")
```
